# Generated by Django 5.0.4 on 2024-05-04 16:54

import app.helpers
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masuk', models.TimeField(default='08:00')),
                ('pulang', models.TimeField(default='17:00')),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('year', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1984), app.helpers.max_value_current_year])),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classs',
            },
        ),
        migrations.AddField(
            model_name='akun',
            name='qr_hash',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(default=app.helpers.get_current_time)),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('absen', 'Absen')], max_length=10)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.akun')),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jadwal')),
            ],
        ),
        migrations.AddField(
            model_name='akun',
            name='kelas',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kelas'),
        ),
    ]
